[WIP]ユーザープロフィール編集ページの作成
yosuke-i-e/freemarket_sample_39f pull request #8
Opened 2019-03-04 05:05 UTC by yosuke-i-e

#What
プロフィール編集ページを作成する

#Why
ユーザーがプロフィールの編集をできるようにするため

2019-03-21 22:56 UTC, yosuke-i-e commented
![スクリーンショット 2019-03-22 7 53 28](https://user-images.githubusercontent.com/44855912/54790039-0084cb00-4c78-11e9-9136-bf408ce16bef.png)

2019-03-22 02:04 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +    @user = User.find(current_user.id)
メソッドに切り分けましょう

2019-03-22 02:04 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +    @user.update(params.require(:user).permit(:nickname, :profile))
エラーハンドリングしましょう

2019-03-24 01:52 UTC, yosuke-i-e commented on app/controllers/users_controller.rb
> +    @user = User.find(current_user.id)
set_userメソッドに切り分けました。

2019-03-24 01:53 UTC, yosuke-i-e commented on app/controllers/users_controller.rb
> +    @user.update(params.require(:user).permit(:nickname, :profile))
updateをupdate!に変更しました。

2019-03-24 02:28 UTC, ghost requested changes

2019-03-24 02:28 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +    @user.update!(params.require(:user).permit(:nickname, :profile))
if @user.update

else

で書いて欲しいです

2019-03-24 05:27 UTC, yosuke-i-e commented on app/controllers/users_controller.rb
> +    @user.update!(params.require(:user).permit(:nickname, :profile))
そのように記述して、エラーが出た場合はエラーメッセージを表示するようにしました。

2019-03-24 05:41 UTC, ghost approved these changes
LGTMです！

2019-03-24 06:15 UTC, yosuke-i-e commented
ありがとうございました。

2019-03-24 06:15 UTC, merged